export interface ThreatActor {
  id:         string;
  name:       string;
  aliases:    string[];
  origin:     string;
  motivation: string[];
  targets:    string[];
  ttps:       Array<{ id: string; name: string }>;
  tlp:        'WHITE' | 'GREEN' | 'AMBER';
  active:     boolean;
}

export const THREAT_ACTORS: ThreatActor[] = [
  {
    id: 'apt28',
    name: 'APT28',
    aliases: ['Fancy Bear', 'Sofacy', 'Pawn Storm', 'STRONTIUM'],
    origin: 'Russia',
    motivation: ['espionage', 'political influence'],
    targets: ['government', 'military', 'aerospace', 'energy'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1566', name: 'Phishing' },
      { id: 'T1078', name: 'Valid Accounts' },
      { id: 'T1071', name: 'Application Layer Protocol' },
      { id: 'T1027', name: 'Obfuscated Files or Information' },
    ],
  },
  {
    id: 'apt29',
    name: 'APT29',
    aliases: ['Cozy Bear', 'The Dukes', 'NOBELIUM', 'Midnight Blizzard'],
    origin: 'Russia',
    motivation: ['espionage', 'intelligence gathering'],
    targets: ['government', 'think tanks', 'healthcare', 'technology'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1195', name: 'Supply Chain Compromise' },
      { id: 'T1566', name: 'Phishing' },
      { id: 'T1190', name: 'Exploit Public-Facing Application' },
      { id: 'T1059', name: 'Command and Scripting Interpreter' },
    ],
  },
  {
    id: 'apt41',
    name: 'APT41',
    aliases: ['Double Dragon', 'Barium', 'Winnti', 'Bronze Atlas'],
    origin: 'China',
    motivation: ['espionage', 'financial gain'],
    targets: ['healthcare', 'technology', 'gaming', 'telecommunications'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1190', name: 'Exploit Public-Facing Application' },
      { id: 'T1133', name: 'External Remote Services' },
      { id: 'T1003', name: 'OS Credential Dumping' },
      { id: 'T1486', name: 'Data Encrypted for Impact' },
    ],
  },
  {
    id: 'lazarus',
    name: 'Lazarus Group',
    aliases: ['HIDDEN COBRA', 'Zinc', 'Guardians of Peace'],
    origin: 'North Korea',
    motivation: ['financial gain', 'espionage', 'sabotage'],
    targets: ['financial', 'cryptocurrency', 'defense', 'media'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1566', name: 'Phishing' },
      { id: 'T1486', name: 'Data Encrypted for Impact' },
      { id: 'T1059', name: 'Command and Scripting Interpreter' },
      { id: 'T1105', name: 'Ingress Tool Transfer' },
    ],
  },
  {
    id: 'sandworm',
    name: 'Sandworm',
    aliases: ['Voodoo Bear', 'Telebots', 'ELECTRUM', 'Seashell Blizzard'],
    origin: 'Russia',
    motivation: ['sabotage', 'disruption', 'espionage'],
    targets: ['energy', 'government', 'media', 'critical infrastructure'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1561', name: 'Disk Wipe' },
      { id: 'T1485', name: 'Data Destruction' },
      { id: 'T1190', name: 'Exploit Public-Facing Application' },
      { id: 'T1071', name: 'Application Layer Protocol' },
    ],
  },
  {
    id: 'volt-typhoon',
    name: 'Volt Typhoon',
    aliases: ['Bronze Silhouette', 'Dev-0391', 'Vanguard Panda'],
    origin: 'China',
    motivation: ['pre-positioning', 'espionage'],
    targets: ['critical infrastructure', 'communications', 'transportation', 'government'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1078', name: 'Valid Accounts' },
      { id: 'T1588', name: 'Obtain Capabilities' },
      { id: 'T1133', name: 'External Remote Services' },
      { id: 'T1036', name: 'Masquerading' },
    ],
  },
  {
    id: 'scattered-spider',
    name: 'Scattered Spider',
    aliases: ['Muddled Libra', 'UNC3944', 'Starfraud'],
    origin: 'Western (English-speaking)',
    motivation: ['financial gain', 'data theft'],
    targets: ['hospitality', 'retail', 'financial', 'telecommunications'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1621', name: 'MFA Request Generation' },
      { id: 'T1534', name: 'Internal Spearphishing' },
      { id: 'T1586', name: 'Compromise Accounts' },
      { id: 'T1557', name: 'Adversary-in-the-Middle' },
    ],
  },
  {
    id: 'muddywater',
    name: 'MuddyWater',
    aliases: ['MERCURY', 'Static Kitten', 'Seedworm'],
    origin: 'Iran',
    motivation: ['espionage', 'intelligence gathering'],
    targets: ['government', 'telecommunications', 'defense', 'oil and gas'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1566', name: 'Phishing' },
      { id: 'T1059', name: 'Command and Scripting Interpreter' },
      { id: 'T1071', name: 'Application Layer Protocol' },
      { id: 'T1547', name: 'Boot or Logon Autostart Execution' },
    ],
  },
  {
    id: 'charming-kitten',
    name: 'Charming Kitten',
    aliases: ['APT35', 'Phosphorus', 'Mint Sandstorm', 'TA453'],
    origin: 'Iran',
    motivation: ['espionage', 'surveillance'],
    targets: ['academics', 'journalists', 'government', 'human rights'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1566', name: 'Phishing' },
      { id: 'T1598', name: 'Phishing for Information' },
      { id: 'T1078', name: 'Valid Accounts' },
      { id: 'T1539', name: 'Steal Web Session Cookie' },
    ],
  },
  {
    id: 'turla',
    name: 'Turla',
    aliases: ['Snake', 'Venomous Bear', 'Waterbug', 'Secret Blizzard'],
    origin: 'Russia',
    motivation: ['espionage'],
    targets: ['government', 'military', 'embassies', 'research'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1071', name: 'Application Layer Protocol' },
      { id: 'T1102', name: 'Web Service' },
      { id: 'T1056', name: 'Input Capture' },
      { id: 'T1560', name: 'Archive Collected Data' },
    ],
  },
  {
    id: 'darkside',
    name: 'DarkSide / BlackMatter',
    aliases: ['Carbon Spider', 'Carbon-B'],
    origin: 'Eastern Europe',
    motivation: ['financial gain'],
    targets: ['energy', 'manufacturing', 'financial', 'healthcare'],
    tlp: 'WHITE',
    active: false,
    ttps: [
      { id: 'T1486', name: 'Data Encrypted for Impact' },
      { id: 'T1657', name: 'Financial Theft' },
      { id: 'T1059', name: 'Command and Scripting Interpreter' },
      { id: 'T1021', name: 'Remote Services' },
    ],
  },
  {
    id: 'lapsus',
    name: 'LAPSUS$',
    aliases: ['DEV-0537', 'Strawberry Tempest'],
    origin: 'UK / South America',
    motivation: ['financial gain', 'notoriety'],
    targets: ['technology', 'telecommunications', 'gaming', 'government'],
    tlp: 'WHITE',
    active: false,
    ttps: [
      { id: 'T1534', name: 'Internal Spearphishing' },
      { id: 'T1621', name: 'MFA Request Generation' },
      { id: 'T1586', name: 'Compromise Accounts' },
      { id: 'T1119', name: 'Automated Collection' },
    ],
  },
  {
    id: 'killnet',
    name: 'KillNet',
    aliases: ['KillMilk'],
    origin: 'Russia',
    motivation: ['hacktivism', 'disruption'],
    targets: ['government', 'healthcare', 'financial', 'media'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1498', name: 'Network Denial of Service' },
      { id: 'T1499', name: 'Endpoint Denial of Service' },
    ],
  },
  {
    id: 'blackcat',
    name: 'BlackCat / ALPHV',
    aliases: ['Noberus'],
    origin: 'Eastern Europe',
    motivation: ['financial gain', 'ransomware-as-a-service'],
    targets: ['healthcare', 'manufacturing', 'legal', 'financial'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1486', name: 'Data Encrypted for Impact' },
      { id: 'T1657', name: 'Financial Theft' },
      { id: 'T1190', name: 'Exploit Public-Facing Application' },
      { id: 'T1078', name: 'Valid Accounts' },
    ],
  },
  {
    id: 'kimsuky',
    name: 'Kimsuky',
    aliases: ['Velvet Chollima', 'Thallium', 'Black Banshee'],
    origin: 'North Korea',
    motivation: ['espionage', 'intelligence gathering'],
    targets: ['think tanks', 'government', 'nuclear policy', 'academics'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1566', name: 'Phishing' },
      { id: 'T1598', name: 'Phishing for Information' },
      { id: 'T1059', name: 'Command and Scripting Interpreter' },
      { id: 'T1071', name: 'Application Layer Protocol' },
    ],
  },
];
