export interface ThreatActor {
  id:         string;
  name:       string;
  aliases:    string[];
  origin:     string;
  motivation: string[];
  targets:    string[];
  ttps:       Array<{ id: string; name: string }>;
  tlp:        'WHITE' | 'GREEN' | 'AMBER';
  active:     boolean;
}

export const THREAT_ACTORS: ThreatActor[] = [
  {
    id: 'apt28',
    name: 'APT28',
    aliases: ['Fancy Bear', 'Sofacy', 'Pawn Storm', 'STRONTIUM'],
    origin: 'Russia',
    motivation: ['espionage', 'political influence'],
    targets: ['government', 'military', 'aerospace', 'energy'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1566', name: 'Phishing' },
      { id: 'T1078', name: 'Valid Accounts' },
      { id: 'T1071', name: 'Application Layer Protocol' },
      { id: 'T1027', name: 'Obfuscated Files or Information' },
    ],
  },
  {
    id: 'apt29',
    name: 'APT29',
    aliases: ['Cozy Bear', 'The Dukes', 'NOBELIUM', 'Midnight Blizzard'],
    origin: 'Russia',
    motivation: ['espionage', 'intelligence gathering'],
    targets: ['government', 'think tanks', 'healthcare', 'technology'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1195', name: 'Supply Chain Compromise' },
      { id: 'T1566', name: 'Phishing' },
      { id: 'T1190', name: 'Exploit Public-Facing Application' },
      { id: 'T1059', name: 'Command and Scripting Interpreter' },
    ],
  },
  {
    id: 'apt41',
    name: 'APT41',
    aliases: ['Double Dragon', 'Barium', 'Winnti', 'Bronze Atlas'],
    origin: 'China',
    motivation: ['espionage', 'financial gain'],
    targets: ['healthcare', 'technology', 'gaming', 'telecommunications'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1190', name: 'Exploit Public-Facing Application' },
      { id: 'T1133', name: 'External Remote Services' },
      { id: 'T1003', name: 'OS Credential Dumping' },
      { id: 'T1486', name: 'Data Encrypted for Impact' },
    ],
  },
  {
    id: 'lazarus',
    name: 'Lazarus Group',
    aliases: ['HIDDEN COBRA', 'Zinc', 'Guardians of Peace'],
    origin: 'North Korea',
    motivation: ['financial gain', 'espionage', 'sabotage'],
    targets: ['financial', 'cryptocurrency', 'defense', 'media'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1566', name: 'Phishing' },
      { id: 'T1486', name: 'Data Encrypted for Impact' },
      { id: 'T1059', name: 'Command and Scripting Interpreter' },
      { id: 'T1105', name: 'Ingress Tool Transfer' },
    ],
  },
  {
    id: 'sandworm',
    name: 'Sandworm',
    aliases: ['Voodoo Bear', 'Telebots', 'ELECTRUM', 'Seashell Blizzard'],
    origin: 'Russia',
    motivation: ['sabotage', 'disruption', 'espionage'],
    targets: ['energy', 'government', 'media', 'critical infrastructure'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1561', name: 'Disk Wipe' },
      { id: 'T1485', name: 'Data Destruction' },
      { id: 'T1190', name: 'Exploit Public-Facing Application' },
      { id: 'T1071', name: 'Application Layer Protocol' },
    ],
  },
  {
    id: 'volt-typhoon',
    name: 'Volt Typhoon',
    aliases: ['Bronze Silhouette', 'Dev-0391', 'Vanguard Panda'],
    origin: 'China',
    motivation: ['pre-positioning', 'espionage'],
    targets: ['critical infrastructure', 'communications', 'transportation', 'government'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1078', name: 'Valid Accounts' },
      { id: 'T1588', name: 'Obtain Capabilities' },
      { id: 'T1133', name: 'External Remote Services' },
      { id: 'T1036', name: 'Masquerading' },
    ],
  },
  {
    id: 'scattered-spider',
    name: 'Scattered Spider',
    aliases: ['Muddled Libra', 'UNC3944', 'Starfraud'],
    origin: 'Western (English-speaking)',
    motivation: ['financial gain', 'data theft'],
    targets: ['hospitality', 'retail', 'financial', 'telecommunications'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1621', name: 'MFA Request Generation' },
      { id: 'T1534', name: 'Internal Spearphishing' },
      { id: 'T1586', name: 'Compromise Accounts' },
      { id: 'T1557', name: 'Adversary-in-the-Middle' },
    ],
  },
  {
    id: 'muddywater',
    name: 'MuddyWater',
    aliases: ['MERCURY', 'Static Kitten', 'Seedworm'],
    origin: 'Iran',
    motivation: ['espionage', 'intelligence gathering'],
    targets: ['government', 'telecommunications', 'defense', 'oil and gas'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1566', name: 'Phishing' },
      { id: 'T1059', name: 'Command and Scripting Interpreter' },
      { id: 'T1071', name: 'Application Layer Protocol' },
      { id: 'T1547', name: 'Boot or Logon Autostart Execution' },
    ],
  },
  {
    id: 'charming-kitten',
    name: 'Charming Kitten',
    aliases: ['APT35', 'Phosphorus', 'Mint Sandstorm', 'TA453'],
    origin: 'Iran',
    motivation: ['espionage', 'surveillance'],
    targets: ['academics', 'journalists', 'government', 'human rights'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1566', name: 'Phishing' },
      { id: 'T1598', name: 'Phishing for Information' },
      { id: 'T1078', name: 'Valid Accounts' },
      { id: 'T1539', name: 'Steal Web Session Cookie' },
    ],
  },
  {
    id: 'turla',
    name: 'Turla',
    aliases: ['Snake', 'Venomous Bear', 'Waterbug', 'Secret Blizzard'],
    origin: 'Russia',
    motivation: ['espionage'],
    targets: ['government', 'military', 'embassies', 'research'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1071', name: 'Application Layer Protocol' },
      { id: 'T1102', name: 'Web Service' },
      { id: 'T1056', name: 'Input Capture' },
      { id: 'T1560', name: 'Archive Collected Data' },
    ],
  },
  {
    id: 'darkside',
    name: 'DarkSide / BlackMatter',
    aliases: ['Carbon Spider', 'Carbon-B'],
    origin: 'Eastern Europe',
    motivation: ['financial gain'],
    targets: ['energy', 'manufacturing', 'financial', 'healthcare'],
    tlp: 'WHITE',
    active: false,
    ttps: [
      { id: 'T1486', name: 'Data Encrypted for Impact' },
      { id: 'T1657', name: 'Financial Theft' },
      { id: 'T1059', name: 'Command and Scripting Interpreter' },
      { id: 'T1021', name: 'Remote Services' },
    ],
  },
  {
    id: 'lapsus',
    name: 'LAPSUS$',
    aliases: ['DEV-0537', 'Strawberry Tempest'],
    origin: 'UK / South America',
    motivation: ['financial gain', 'notoriety'],
    targets: ['technology', 'telecommunications', 'gaming', 'government'],
    tlp: 'WHITE',
    active: false,
    ttps: [
      { id: 'T1534', name: 'Internal Spearphishing' },
      { id: 'T1621', name: 'MFA Request Generation' },
      { id: 'T1586', name: 'Compromise Accounts' },
      { id: 'T1119', name: 'Automated Collection' },
    ],
  },
  {
    id: 'killnet',
    name: 'KillNet',
    aliases: ['KillMilk'],
    origin: 'Russia',
    motivation: ['hacktivism', 'disruption'],
    targets: ['government', 'healthcare', 'financial', 'media'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1498', name: 'Network Denial of Service' },
      { id: 'T1499', name: 'Endpoint Denial of Service' },
    ],
  },
  {
    id: 'blackcat',
    name: 'BlackCat / ALPHV',
    aliases: ['Noberus'],
    origin: 'Eastern Europe',
    motivation: ['financial gain', 'ransomware-as-a-service'],
    targets: ['healthcare', 'manufacturing', 'legal', 'financial'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1486', name: 'Data Encrypted for Impact' },
      { id: 'T1657', name: 'Financial Theft' },
      { id: 'T1190', name: 'Exploit Public-Facing Application' },
      { id: 'T1078', name: 'Valid Accounts' },
    ],
  },
  {
    id: 'kimsuky',
    name: 'Kimsuky',
    aliases: ['Velvet Chollima', 'Thallium', 'Black Banshee'],
    origin: 'North Korea',
    motivation: ['espionage', 'intelligence gathering'],
    targets: ['think tanks', 'government', 'nuclear policy', 'academics'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1566', name: 'Phishing' },
      { id: 'T1598', name: 'Phishing for Information' },
      { id: 'T1059', name: 'Command and Scripting Interpreter' },
      { id: 'T1071', name: 'Application Layer Protocol' },
    ],
  },

  // ─── Russia (additional) ──────────────────────────────────────────────────
  {
    id: 'gamaredon',
    name: 'Gamaredon',
    aliases: ['Primitive Bear', 'Armageddon', 'Trident Ursa', 'UAC-0010', 'ACTINIUM'],
    origin: 'Russia',
    motivation: ['espionage', 'disruption'],
    targets: ['Ukrainian government', 'military', 'law enforcement', 'NGOs'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1566', name: 'Phishing' },
      { id: 'T1547', name: 'Boot or Logon Autostart Execution' },
      { id: 'T1071', name: 'Application Layer Protocol' },
      { id: 'T1105', name: 'Ingress Tool Transfer' },
    ],
  },
  {
    id: 'ember-bear',
    name: 'Ember Bear',
    aliases: ['UAC-0056', 'Lorec53', 'Saint Bear', 'Bleeding Bear', 'TA471'],
    origin: 'Russia',
    motivation: ['sabotage', 'disruption'],
    targets: ['Ukraine critical infrastructure', 'energy', 'government'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1485', name: 'Data Destruction' },
      { id: 'T1561', name: 'Disk Wipe' },
      { id: 'T1566', name: 'Phishing' },
      { id: 'T1059', name: 'Command and Scripting Interpreter' },
    ],
  },
  {
    id: 'cold-river',
    name: 'Cold River',
    aliases: ['Callisto Group', 'Star Blizzard', 'TA446', 'Seaborgium', 'COLDRIVER'],
    origin: 'Russia',
    motivation: ['espionage', 'intelligence gathering'],
    targets: ['NATO officials', 'government', 'think tanks', 'journalists', 'NGOs'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1598', name: 'Phishing for Information' },
      { id: 'T1566', name: 'Phishing' },
      { id: 'T1539', name: 'Steal Web Session Cookie' },
      { id: 'T1078', name: 'Valid Accounts' },
    ],
  },
  {
    id: 'noname057',
    name: 'NoName057(16)',
    aliases: ['NoName', '05716nnm', 'DDOSIA Project'],
    origin: 'Russia',
    motivation: ['hacktivism', 'disruption'],
    targets: ['NATO governments', 'Ukraine-aligned states', 'transportation', 'financial'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1498', name: 'Network Denial of Service' },
      { id: 'T1583', name: 'Acquire Infrastructure' },
    ],
  },
  {
    id: 'energetic-bear',
    name: 'Energetic Bear',
    aliases: ['Dragonfly', 'Crouching Yeti', 'DYMALLOY', 'Berserk Bear', 'Temp.Isotope'],
    origin: 'Russia',
    motivation: ['espionage', 'sabotage', 'pre-positioning'],
    targets: ['energy', 'industrial control systems', 'aviation', 'government'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1190', name: 'Exploit Public-Facing Application' },
      { id: 'T1133', name: 'External Remote Services' },
      { id: 'T1078', name: 'Valid Accounts' },
      { id: 'T1059', name: 'Command and Scripting Interpreter' },
    ],
  },

  // ─── China (additional) ───────────────────────────────────────────────────
  {
    id: 'apt1',
    name: 'APT1',
    aliases: ['Comment Crew', 'Comment Panda', 'PLA Unit 61398', 'Byzantine Hades'],
    origin: 'China',
    motivation: ['espionage', 'IP theft'],
    targets: ['aerospace', 'energy', 'technology', 'financial'],
    tlp: 'WHITE',
    active: false,
    ttps: [
      { id: 'T1566', name: 'Phishing' },
      { id: 'T1003', name: 'OS Credential Dumping' },
      { id: 'T1041', name: 'Exfiltration Over C2 Channel' },
      { id: 'T1560', name: 'Archive Collected Data' },
    ],
  },
  {
    id: 'apt10',
    name: 'APT10',
    aliases: ['Stone Panda', 'MenuPass', 'ChessMaster', 'POTASSIUM', 'Red Apollo'],
    origin: 'China',
    motivation: ['espionage', 'supply chain compromise'],
    targets: ['MSP/IT supply chain', 'government', 'healthcare', 'manufacturing'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1195', name: 'Supply Chain Compromise' },
      { id: 'T1078', name: 'Valid Accounts' },
      { id: 'T1071', name: 'Application Layer Protocol' },
      { id: 'T1560', name: 'Archive Collected Data' },
    ],
  },
  {
    id: 'apt40',
    name: 'APT40',
    aliases: ['Leviathan', 'TEMP.Periscope', 'Bronze Mohawk', 'MUDCARP', 'Kryptonite Panda'],
    origin: 'China',
    motivation: ['espionage'],
    targets: ['maritime', 'naval', 'defense', 'academia', 'government'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1566', name: 'Phishing' },
      { id: 'T1190', name: 'Exploit Public-Facing Application' },
      { id: 'T1078', name: 'Valid Accounts' },
      { id: 'T1005', name: 'Data from Local System' },
    ],
  },
  {
    id: 'hafnium',
    name: 'Hafnium',
    aliases: ['Silk Typhoon', 'HAFNIUM'],
    origin: 'China',
    motivation: ['espionage'],
    targets: ['defense contractors', 'law firms', 'universities', 'NGOs', 'infectious disease researchers'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1190', name: 'Exploit Public-Facing Application' },
      { id: 'T1505', name: 'Server Software Component (Web Shell)' },
      { id: 'T1003', name: 'OS Credential Dumping' },
      { id: 'T1560', name: 'Archive Collected Data' },
    ],
  },
  {
    id: 'salt-typhoon',
    name: 'Salt Typhoon',
    aliases: ['GhostEmperor', 'Earth Estries', 'UNC2286', 'FamousSparrow'],
    origin: 'China',
    motivation: ['espionage', 'persistent access'],
    targets: ['telecom carriers', 'ISPs', 'government', 'technology'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1190', name: 'Exploit Public-Facing Application' },
      { id: 'T1078', name: 'Valid Accounts' },
      { id: 'T1048', name: 'Exfiltration Over Alternative Protocol' },
      { id: 'T1133', name: 'External Remote Services' },
    ],
  },
  {
    id: 'flax-typhoon',
    name: 'Flax Typhoon',
    aliases: ['Ethereal Panda', 'Redfly'],
    origin: 'China',
    motivation: ['espionage', 'pre-positioning'],
    targets: ['Taiwan government', 'utilities', 'education', 'manufacturing'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1078', name: 'Valid Accounts' },
      { id: 'T1036', name: 'Masquerading' },
      { id: 'T1133', name: 'External Remote Services' },
      { id: 'T1021', name: 'Remote Services' },
    ],
  },
  {
    id: 'apt3',
    name: 'APT3',
    aliases: ['Gothic Panda', 'UPS', 'TG-0110', 'Buckeye', 'Clandestine Fox'],
    origin: 'China',
    motivation: ['espionage'],
    targets: ['defense', 'aerospace', 'technology', 'construction'],
    tlp: 'WHITE',
    active: false,
    ttps: [
      { id: 'T1190', name: 'Exploit Public-Facing Application' },
      { id: 'T1059', name: 'Command and Scripting Interpreter' },
      { id: 'T1003', name: 'OS Credential Dumping' },
      { id: 'T1071', name: 'Application Layer Protocol' },
    ],
  },

  // ─── North Korea (additional) ─────────────────────────────────────────────
  {
    id: 'apt37',
    name: 'APT37',
    aliases: ['Reaper', 'ScarCruft', 'InkySquid', 'Group123', 'Ricochet Chollima'],
    origin: 'North Korea',
    motivation: ['espionage', 'surveillance'],
    targets: ['South Korea', 'human rights organizations', 'defectors', 'journalists'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1566', name: 'Phishing' },
      { id: 'T1059', name: 'Command and Scripting Interpreter' },
      { id: 'T1056', name: 'Input Capture' },
      { id: 'T1071', name: 'Application Layer Protocol' },
    ],
  },
  {
    id: 'apt38',
    name: 'APT38',
    aliases: ['Stardust Chollima', 'Nickel Gladstone', 'Lazarus Financial Unit'],
    origin: 'North Korea',
    motivation: ['financial gain'],
    targets: ['SWIFT banking', 'financial institutions', 'central banks'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1657', name: 'Financial Theft' },
      { id: 'T1485', name: 'Data Destruction' },
      { id: 'T1059', name: 'Command and Scripting Interpreter' },
      { id: 'T1078', name: 'Valid Accounts' },
    ],
  },
  {
    id: 'andariel',
    name: 'Andariel',
    aliases: ['Onyx Sleet', 'Silent Chollima', 'APT45', 'Stonefly', 'DarkSeoul'],
    origin: 'North Korea',
    motivation: ['espionage', 'financial gain'],
    targets: ['healthcare', 'defense', 'nuclear', 'financial'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1190', name: 'Exploit Public-Facing Application' },
      { id: 'T1486', name: 'Data Encrypted for Impact' },
      { id: 'T1059', name: 'Command and Scripting Interpreter' },
      { id: 'T1003', name: 'OS Credential Dumping' },
    ],
  },
  {
    id: 'bluenoroff',
    name: 'BlueNoroff',
    aliases: ['TA444', 'Stardust Chollima (financial arm)', 'Nickel Academy'],
    origin: 'North Korea',
    motivation: ['financial gain'],
    targets: ['cryptocurrency exchanges', 'banks', 'DeFi protocols', 'fintech'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1657', name: 'Financial Theft' },
      { id: 'T1566', name: 'Phishing' },
      { id: 'T1195', name: 'Supply Chain Compromise' },
      { id: 'T1059', name: 'Command and Scripting Interpreter' },
    ],
  },

  // ─── Iran (additional) ────────────────────────────────────────────────────
  {
    id: 'apt33',
    name: 'APT33',
    aliases: ['Elfin', 'Refined Kitten', 'Holmium', 'MAGNALLIUM', 'Peach Sandstorm'],
    origin: 'Iran',
    motivation: ['espionage', 'sabotage'],
    targets: ['aviation', 'energy', 'petrochemical', 'military'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1566', name: 'Phishing' },
      { id: 'T1078', name: 'Valid Accounts' },
      { id: 'T1485', name: 'Data Destruction' },
      { id: 'T1059', name: 'Command and Scripting Interpreter' },
    ],
  },
  {
    id: 'apt34',
    name: 'APT34',
    aliases: ['OilRig', 'Helix Kitten', 'Cobalt Gypsy', 'EUROPIUM', 'Hazel Sandstorm'],
    origin: 'Iran',
    motivation: ['espionage', 'intelligence gathering'],
    targets: ['Gulf government', 'energy', 'financial', 'telecommunications'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1566', name: 'Phishing' },
      { id: 'T1505', name: 'Server Software Component (Web Shell)' },
      { id: 'T1071', name: 'Application Layer Protocol' },
      { id: 'T1560', name: 'Archive Collected Data' },
    ],
  },
  {
    id: 'apt39',
    name: 'APT39',
    aliases: ['Chafer', 'Remix Kitten', 'ITG07', 'Ballistic Bobcat'],
    origin: 'Iran',
    motivation: ['surveillance', 'tracking'],
    targets: ['telecom', 'travel industry', 'high-value individuals', 'journalists'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1566', name: 'Phishing' },
      { id: 'T1056', name: 'Input Capture' },
      { id: 'T1113', name: 'Screen Capture' },
      { id: 'T1071', name: 'Application Layer Protocol' },
    ],
  },
  {
    id: 'tortoiseshell',
    name: 'Tortoiseshell',
    aliases: ['Imperial Kitten', 'TA456', 'Yellow Garuda', 'CRIMSON SANDSTORM'],
    origin: 'Iran',
    motivation: ['espionage', 'supply chain compromise'],
    targets: ['IT supply chain', 'Gulf region', 'defense', 'maritime'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1195', name: 'Supply Chain Compromise' },
      { id: 'T1566', name: 'Phishing' },
      { id: 'T1059', name: 'Command and Scripting Interpreter' },
      { id: 'T1078', name: 'Valid Accounts' },
    ],
  },
  {
    id: 'moses-staff',
    name: 'Moses Staff',
    aliases: ["Abraham's Ax", 'PHOSPHORUS sub-group'],
    origin: 'Iran',
    motivation: ['disruption', 'espionage', 'information operations'],
    targets: ['Israel', 'financial', 'government', 'media'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1485', name: 'Data Destruction' },
      { id: 'T1486', name: 'Data Encrypted for Impact' },
      { id: 'T1190', name: 'Exploit Public-Facing Application' },
      { id: 'T1059', name: 'Command and Scripting Interpreter' },
    ],
  },
  {
    id: 'agrius',
    name: 'Agrius',
    aliases: ['Pink Sandstorm', 'AMERICIUM', 'BlackShadow'],
    origin: 'Iran',
    motivation: ['sabotage', 'disruption'],
    targets: ['Israel', 'diamond industry', 'insurance', 'government'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1485', name: 'Data Destruction' },
      { id: 'T1561', name: 'Disk Wipe' },
      { id: 'T1190', name: 'Exploit Public-Facing Application' },
      { id: 'T1657', name: 'Financial Theft' },
    ],
  },

  // ─── Other State Actors ───────────────────────────────────────────────────
  {
    id: 'oceanlotus',
    name: 'OceanLotus',
    aliases: ['APT32', 'Canvas Cyclone', 'SeaLotus', 'Cobalt Kitty'],
    origin: 'Vietnam',
    motivation: ['espionage', 'political surveillance'],
    targets: ['Southeast Asian governments', 'journalists', 'dissidents', 'foreign corporations'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1566', name: 'Phishing' },
      { id: 'T1059', name: 'Command and Scripting Interpreter' },
      { id: 'T1071', name: 'Application Layer Protocol' },
      { id: 'T1027', name: 'Obfuscated Files or Information' },
    ],
  },
  {
    id: 'sidewinder',
    name: 'SideWinder',
    aliases: ['Rattlesnake', 'T-APT-04', 'Hardcore Nationalist', 'RAZOR TIGER'],
    origin: 'India',
    motivation: ['espionage'],
    targets: ['Pakistan military', 'government', 'Afghanistan', 'China border regions'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1566', name: 'Phishing' },
      { id: 'T1203', name: 'Exploitation for Client Execution' },
      { id: 'T1071', name: 'Application Layer Protocol' },
      { id: 'T1059', name: 'Command and Scripting Interpreter' },
    ],
  },
  {
    id: 'transparent-tribe',
    name: 'Transparent Tribe',
    aliases: ['APT36', 'ProjectM', 'C-Major', 'Mythic Leopard', 'Operation C-Major'],
    origin: 'Pakistan',
    motivation: ['espionage'],
    targets: ['Indian military', 'government', 'defense contractors', 'students'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1566', name: 'Phishing' },
      { id: 'T1105', name: 'Ingress Tool Transfer' },
      { id: 'T1059', name: 'Command and Scripting Interpreter' },
      { id: 'T1056', name: 'Input Capture' },
    ],
  },
  {
    id: 'ta423',
    name: 'TA423 / APT43',
    aliases: ['APT43', 'Red Dev 6', 'Kimsuky sub-unit', 'Velvet Chollima variant', 'ARCHIPELAGO'],
    origin: 'North Korea',
    motivation: ['espionage', 'financial gain'],
    targets: ['cryptocurrency', 'South Korea', 'nuclear policy', 'US government'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1566', name: 'Phishing' },
      { id: 'T1657', name: 'Financial Theft' },
      { id: 'T1598', name: 'Phishing for Information' },
      { id: 'T1586', name: 'Compromise Accounts' },
    ],
  },

  // ─── Ransomware Groups ────────────────────────────────────────────────────
  {
    id: 'lockbit',
    name: 'LockBit',
    aliases: ['LockBit 3.0', 'Bitwise Spider', 'ABCD Ransomware'],
    origin: 'Eastern Europe',
    motivation: ['financial gain', 'ransomware-as-a-service'],
    targets: ['healthcare', 'government', 'manufacturing', 'legal', 'critical infrastructure'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1486', name: 'Data Encrypted for Impact' },
      { id: 'T1190', name: 'Exploit Public-Facing Application' },
      { id: 'T1078', name: 'Valid Accounts' },
      { id: 'T1657', name: 'Financial Theft' },
    ],
  },
  {
    id: 'clop',
    name: 'Cl0p',
    aliases: ['TA505', 'GRACEFUL SPIDER', 'Clop'],
    origin: 'Eastern Europe',
    motivation: ['financial gain', 'mass data extortion'],
    targets: ['financial', 'healthcare', 'technology', 'retail'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1190', name: 'Exploit Public-Facing Application' },
      { id: 'T1486', name: 'Data Encrypted for Impact' },
      { id: 'T1657', name: 'Financial Theft' },
      { id: 'T1041', name: 'Exfiltration Over C2 Channel' },
    ],
  },
  {
    id: 'ransomhub',
    name: 'RansomHub',
    aliases: ['Cyclops', 'Knight Ransomware (successor)'],
    origin: 'Unknown',
    motivation: ['financial gain', 'ransomware-as-a-service'],
    targets: ['critical infrastructure', 'healthcare', 'government', 'water systems'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1486', name: 'Data Encrypted for Impact' },
      { id: 'T1190', name: 'Exploit Public-Facing Application' },
      { id: 'T1078', name: 'Valid Accounts' },
      { id: 'T1657', name: 'Financial Theft' },
    ],
  },
  {
    id: 'play',
    name: 'Play',
    aliases: ['PlayCrypt', 'Fiddling Scorpius'],
    origin: 'Eastern Europe',
    motivation: ['financial gain'],
    targets: ['VMware ESXi', 'manufacturing', 'government', 'telecommunications'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1486', name: 'Data Encrypted for Impact' },
      { id: 'T1190', name: 'Exploit Public-Facing Application' },
      { id: 'T1078', name: 'Valid Accounts' },
      { id: 'T1562', name: 'Impair Defenses' },
    ],
  },
  {
    id: 'black-basta',
    name: 'Black Basta',
    aliases: ['UNC4393', 'Conti successor'],
    origin: 'Russia',
    motivation: ['financial gain', 'ransomware-as-a-service'],
    targets: ['healthcare', 'manufacturing', 'financial', 'critical infrastructure'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1486', name: 'Data Encrypted for Impact' },
      { id: 'T1566', name: 'Phishing' },
      { id: 'T1059', name: 'Command and Scripting Interpreter' },
      { id: 'T1021', name: 'Remote Services' },
    ],
  },
  {
    id: 'akira',
    name: 'Akira',
    aliases: ['Storm-1567'],
    origin: 'Eastern Europe',
    motivation: ['financial gain'],
    targets: ['VMware ESXi', 'Linux systems', 'SMBs', 'manufacturing'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1486', name: 'Data Encrypted for Impact' },
      { id: 'T1078', name: 'Valid Accounts' },
      { id: 'T1021', name: 'Remote Services' },
      { id: 'T1657', name: 'Financial Theft' },
    ],
  },
  {
    id: 'rhysida',
    name: 'Rhysida',
    aliases: ['Vice Society sub-group (suspected)'],
    origin: 'Unknown',
    motivation: ['financial gain'],
    targets: ['healthcare', 'government', 'education', 'manufacturing'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1486', name: 'Data Encrypted for Impact' },
      { id: 'T1566', name: 'Phishing' },
      { id: 'T1078', name: 'Valid Accounts' },
      { id: 'T1657', name: 'Financial Theft' },
    ],
  },
  {
    id: 'royal',
    name: 'Royal / BlackSuit',
    aliases: ['BlackSuit', 'Storm-0647', 'Conti sub-group'],
    origin: 'Eastern Europe',
    motivation: ['financial gain'],
    targets: ['critical infrastructure', 'healthcare', 'education', 'communications'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1486', name: 'Data Encrypted for Impact' },
      { id: 'T1566', name: 'Phishing' },
      { id: 'T1078', name: 'Valid Accounts' },
      { id: 'T1021', name: 'Remote Services' },
    ],
  },
  {
    id: '8base',
    name: '8Base',
    aliases: ['RansomHouse variant (suspected)'],
    origin: 'Unknown',
    motivation: ['financial gain', 'data extortion'],
    targets: ['SMBs', 'professional services', 'manufacturing', 'financial'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1486', name: 'Data Encrypted for Impact' },
      { id: 'T1657', name: 'Financial Theft' },
      { id: 'T1059', name: 'Command and Scripting Interpreter' },
      { id: 'T1078', name: 'Valid Accounts' },
    ],
  },

  // ─── Financial Crime ──────────────────────────────────────────────────────
  {
    id: 'evil-corp',
    name: 'Evil Corp',
    aliases: ['Indrik Spider', 'UNC2165', 'Dridex Gang', 'Entropy', 'Macaroni'],
    origin: 'Russia',
    motivation: ['financial gain'],
    targets: ['financial', 'government', 'healthcare', 'manufacturing'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1486', name: 'Data Encrypted for Impact' },
      { id: 'T1566', name: 'Phishing' },
      { id: 'T1657', name: 'Financial Theft' },
      { id: 'T1059', name: 'Command and Scripting Interpreter' },
    ],
  },
  {
    id: 'fin7',
    name: 'FIN7',
    aliases: ['Carbanak', 'Sangria Tempest', 'Navigator Group', 'ELBRUS', 'Carbon Spider'],
    origin: 'Eastern Europe',
    motivation: ['financial gain'],
    targets: ['restaurant/hospitality POS', 'retail', 'financial services', 'technology'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1566', name: 'Phishing' },
      { id: 'T1657', name: 'Financial Theft' },
      { id: 'T1059', name: 'Command and Scripting Interpreter' },
      { id: 'T1056', name: 'Input Capture' },
    ],
  },

  // ─── Hacktivists ──────────────────────────────────────────────────────────
  {
    id: 'anonymous-sudan',
    name: 'Anonymous Sudan',
    aliases: ['Storm-1359', 'ANONSUD'],
    origin: 'Sudan (Russia-linked)',
    motivation: ['hacktivism', 'disruption'],
    targets: ['Western governments', 'healthcare', 'aviation', 'financial'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1498', name: 'Network Denial of Service' },
      { id: 'T1499', name: 'Endpoint Denial of Service' },
      { id: 'T1583', name: 'Acquire Infrastructure' },
    ],
  },
  {
    id: 'it-army-ukraine',
    name: 'IT Army of Ukraine',
    aliases: ['Ukrainian Cyber Volunteers'],
    origin: 'Ukraine',
    motivation: ['hacktivism', 'disruption'],
    targets: ['Russian government', 'Russian financial', 'Russian media', 'Russian infrastructure'],
    tlp: 'WHITE',
    active: true,
    ttps: [
      { id: 'T1498', name: 'Network Denial of Service' },
      { id: 'T1499', name: 'Endpoint Denial of Service' },
    ],
  },
];
