import type { Theater } from '@/types';

export const THEATERS: Theater[] = [
  {
    id: 'gcc',
    name: 'Gulf Cooperation Council',
    shortName: 'GCC',
    description: 'Persian Gulf states including Saudi Arabia, UAE, Qatar, Kuwait, Bahrain, and Oman',
    lat: 25.0,
    lng: 50.5,
    zoom: 5,
    countries: ['SA', 'AE', 'QA', 'KW', 'BH', 'OM'],
    color: '#f59e0b',
  },
  {
    id: 'eastern-europe',
    name: 'Eastern Europe',
    shortName: 'EE',
    description: 'Ukraine, Moldova, and surrounding conflict zones',
    lat: 49.0,
    lng: 32.0,
    zoom: 5,
    countries: ['UA', 'MD', 'BY', 'PL', 'RO'],
    color: '#ef4444',
  },
  {
    id: 'indo-pacific',
    name: 'Indo-Pacific',
    shortName: 'INDOPAC',
    description: 'South China Sea, Taiwan Strait, and broader Indo-Pacific region',
    lat: 20.0,
    lng: 120.0,
    zoom: 4,
    countries: ['CN', 'TW', 'PH', 'VN', 'JP', 'KR', 'IN'],
    color: '#3b82f6',
  },
  {
    id: 'sahel',
    name: 'Sahel & West Africa',
    shortName: 'SAHEL',
    description: 'Sahel region including Mali, Niger, Burkina Faso, and Lake Chad Basin',
    lat: 15.0,
    lng: 0.0,
    zoom: 4,
    countries: ['ML', 'NE', 'BF', 'TD', 'MR', 'NG'],
    color: '#f97316',
  },
  {
    id: 'levant',
    name: 'Levant',
    shortName: 'LEVANT',
    description: 'Israel-Gaza, Lebanon, Syria, and surrounding areas',
    lat: 33.0,
    lng: 36.0,
    zoom: 6,
    countries: ['IL', 'PS', 'LB', 'SY', 'JO'],
    color: '#dc2626',
  },
  {
    id: 'horn-of-africa',
    name: 'Horn of Africa',
    shortName: 'HOA',
    description: 'Somalia, Ethiopia, Eritrea, Djibouti, and Red Sea corridor',
    lat: 8.0,
    lng: 44.0,
    zoom: 5,
    countries: ['SO', 'ET', 'ER', 'DJ', 'YE'],
    color: '#8b5cf6',
  },
  {
    id: 'south-asia',
    name: 'South Asia',
    shortName: 'SASIA',
    description: 'Pakistan, Afghanistan, India border regions',
    lat: 28.0,
    lng: 68.0,
    zoom: 5,
    countries: ['PK', 'AF', 'IN', 'BD'],
    color: '#06b6d4',
  },
  {
    id: 'latin-america',
    name: 'Latin America',
    shortName: 'LATAM',
    description: 'Mexico, Central America, Venezuela, and Andean region',
    lat: 4.0,
    lng: -74.0,
    zoom: 3,
    countries: ['MX', 'CO', 'VE', 'GT', 'HN', 'SV', 'PE'],
    color: '#10b981',
  },
];

export function getTheater(id: string): Theater | undefined {
  return THEATERS.find((t) => t.id === id);
}
